/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectdesktop;

import Model.Cd;
import Model.Doos;
import Service.CdService;
import Service.DoosService;
import java.awt.event.WindowListener;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Arno
 */
public class FrmZoekCd extends javax.swing.JFrame
{

    List<Cd> lijst;
    List<Doos> dozen;

    public void vulListBox()
    {
        lstCd.setListData(lijst.toArray());
    }

    /**
     * Creates new form FrmZoekCd
     */
    public FrmZoekCd()
    {
        initComponents();
        lijst = CdService.selectAll();
        vulListBox();
        dozen = DoosService.selectAll();
        cboDoosZoek.addItem("");
        for (Doos d : dozen)
        {
            cboDoosZoek.addItem(d);
        }
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCd = new javax.swing.JList();
        lblTitelZoek = new javax.swing.JLabel();
        txtTitelZoek = new javax.swing.JTextField();
        lblArtiestZoek = new javax.swing.JLabel();
        txtArtiestZoek = new javax.swing.JTextField();
        lblDoosZoek = new javax.swing.JLabel();
        cboDoosZoek = new javax.swing.JComboBox();
        btnZoek = new javax.swing.JButton();
        btnSelecteer = new javax.swing.JButton();
        lblTitelDetails = new javax.swing.JLabel();
        txtTitelDetails = new javax.swing.JTextField();
        lblArtiestDetails = new javax.swing.JLabel();
        txtArtiestDetails = new javax.swing.JTextField();
        lblDoosDetails = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        txtDoosDetails = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstCd.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                lstCdValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCd);

        lblTitelZoek.setText("Titel: ");

        lblArtiestZoek.setText("Artiest: ");

        lblDoosZoek.setText("Doos: ");

        btnZoek.setText("Zoek");
        btnZoek.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnZoekActionPerformed(evt);
            }
        });

        btnSelecteer.setText("Selecteer");
        btnSelecteer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSelecteerActionPerformed(evt);
            }
        });

        lblTitelDetails.setText("Titel: ");

        txtTitelDetails.setEnabled(false);

        lblArtiestDetails.setText("Artiest: ");

        txtArtiestDetails.setEnabled(false);

        lblDoosDetails.setText("Doos: ");

        lblDetails.setText("Details: ");

        txtDoosDetails.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitelZoek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTitelZoek, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitelDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTitelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArtiestZoek)
                                    .addComponent(lblDoosZoek))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtArtiestZoek, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(cboDoosZoek, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnZoek)
                            .addComponent(btnSelecteer)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArtiestDetails)
                                    .addComponent(lblDoosDetails))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtArtiestDetails)
                                    .addComponent(txtDoosDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblDetails))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitelZoek)
                            .addComponent(txtTitelZoek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArtiestZoek)
                            .addComponent(txtArtiestZoek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoosZoek)
                            .addComponent(cboDoosZoek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZoek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(lblDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitelDetails)
                            .addComponent(txtTitelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArtiestDetails)
                            .addComponent(txtArtiestDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoosDetails)
                            .addComponent(txtDoosDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSelecteer))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZoekActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnZoekActionPerformed
    {//GEN-HEADEREND:event_btnZoekActionPerformed
        Doos doos = null;
        if (cboDoosZoek.getSelectedIndex() != 0)
        {
            doos = (Doos) cboDoosZoek.getSelectedItem();
        }
        lijst = CdService.selectWhere(txtTitelZoek.getText(), txtArtiestZoek.getText(), doos);
        vulListBox();
        txtTitelDetails.setText("");
        txtArtiestDetails.setText("");
        txtDoosDetails.setText("");
    }//GEN-LAST:event_btnZoekActionPerformed

    private void lstCdValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_lstCdValueChanged
    {//GEN-HEADEREND:event_lstCdValueChanged
        if (lstCd.getSelectedIndex() != -1)
        {
            Cd cd = (Cd) lstCd.getSelectedValue();
            txtTitelDetails.setText(cd.getTitel());
            txtArtiestDetails.setText(cd.getArtiest());
            txtDoosDetails.setText((cd.getDoos().toString()));
        }
    }//GEN-LAST:event_lstCdValueChanged

    private void btnSelecteerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSelecteerActionPerformed
    {//GEN-HEADEREND:event_btnSelecteerActionPerformed
        if (lstCd.getSelectedIndex() >= 0)
        {
            Start.cd = (Cd)lstCd.getSelectedValue();
            
            WindowListener[] windowListeners = this.getWindowListeners();
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "geen geldige cd");
        }
    }//GEN-LAST:event_btnSelecteerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmZoekCd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmZoekCd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmZoekCd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmZoekCd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrmZoekCd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecteer;
    private javax.swing.JButton btnZoek;
    private javax.swing.JComboBox cboDoosZoek;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArtiestDetails;
    private javax.swing.JLabel lblArtiestZoek;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblDoosDetails;
    private javax.swing.JLabel lblDoosZoek;
    private javax.swing.JLabel lblTitelDetails;
    private javax.swing.JLabel lblTitelZoek;
    private javax.swing.JList lstCd;
    private javax.swing.JTextField txtArtiestDetails;
    private javax.swing.JTextField txtArtiestZoek;
    private javax.swing.JTextField txtDoosDetails;
    private javax.swing.JTextField txtTitelDetails;
    private javax.swing.JTextField txtTitelZoek;
    // End of variables declaration//GEN-END:variables
}
